# QUIZ

11. จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

In [2]:
import numpy as np
ans11 = np.random.rand(1)
print(ans11)

[0.68894744]


12. จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

In [3]:
import numpy as np
ans12 = np.random.randint(50,101,(4,4))
print(ans12)
print(ans12.T)

[[87 81 51 87]
 [56 84 83 95]
 [95 70 58 66]
 [57 83 72 52]]
[[87 56 95 57]
 [81 84 70 83]
 [51 83 58 72]
 [87 95 66 52]]


13. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14

In [9]:
import numpy as np
sol = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
ans13 = sol[1:3,2:4]
print(ans13)

[[ 8  9]
 [13 14]]


14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

In [10]:
import numpy as np
sol = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
ans14 = sol[3,2:]
print(ans14)

[18 19 20]


15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

In [11]:
import numpy as np
sol = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
ans15 = sol[3:,:2]
print(ans15)

[[16 17]
 [21 22]]


16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

In [13]:
import numpy as np
sol = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
ans16 = sol[:3]
print(ans16)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


17. จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

In [19]:
import numpy as np
ans17 = np.arange(1,26)
ans17.shape = (5,5)
print(ans17)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


18. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า 50 และปริ้นออกมา

In [36]:
import numpy as np
pro1 = np.random.randint(10,101,(5,5))
for i in pro1.tolist():
    for j in i:
        if j > 50:
            print(j)


72
60
74
57
51
56
76
100
73
89
96
96
53


19. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่ามากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

In [30]:
import numpy as np
pro2 = np.random.randint(10,101,(5,5))
ans19 = list(pro2[pro2>40])
print(ans19)

[88, 71, 84, 54, 97, 65, 49, 86, 71, 93, 88, 48, 58, 60, 48]


20. เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 3x3 และ transpose และหาเลขอยู่ตำแหน่งที่ (2,2)

In [35]:
import numpy as np
lst = []
for i in range(9):
    while True:
        ini = int(input('กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : '))
        if ini not in lst and ini >= 10 and ini <= 100:
            lst.append(ini)
            break
        elif ini in lst:
            print('กรุณาอย่ากรอกซ้ำ')
        else:
            print("กรุณากรอกให้อยู่ในช่วง 10-100")
            
fin = np.array(lst)
fin.shape = (3,3)
ans20 =  fin.T
print('ตำแหน่งที่ (2,2) คือ : ', ans20[2,2])

กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 1
กรุณากรอกให้อยู่ในช่วง 10-100
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 10
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 10
กรุณาอย่ากรอกซ้ำ
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 11
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 12
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 13
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 14
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 1
กรุณากรอกให้อยู่ในช่วง 10-100
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 15
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 16
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 17
กรุณากรอกตัวเลขที่ไม่ซ้ำกันในช่วง 10 - 100 : 18
ตำแหน่งที่ (2,2) คือ :  18
